const mentalHealthResources = [
    {
      id: 1,
      category: 'Online Therapy Platforms',
      name: 'BetterHelp',
      description: 'Description of BetterHelp.',
      website: 'https://www.betterhelp.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 2,
      category: 'Online Therapy Platforms',
      name: 'Talkspace',
      description: 'Description of Talkspace.',
      website: 'https://www.talkspace.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 3,
      category: 'Online Therapy Platforms',
      name: '7 Cups',
      description: 'Description of 7 Cups.',
      website: 'https://www.7cups.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 4,
      category: 'Online Therapy Platforms',
      name: 'Regain (formerly ReGain)',
      description: 'Description of Regain.',
      website: 'https://www.regain.us/',
      offersOnlineCounseling: true,
    },
    {
      id: 5,
      category: 'Mental Health Apps',
      name: 'Calm',
      description: 'Description of Calm.',
      website: 'https://www.calm.com/',
      offersOnlineCounseling: false,
    },
    {
      id: 6,
      category: 'Mental Health Apps',
      name: 'Headspace',
      description: 'Description of Headspace.',
      website: 'https://www.headspace.com/',
      offersOnlineCounseling: false,
    },
    {
      id: 7,
      category: 'Mental Health Apps',
      name: 'Sanvello (formerly Pacifica)',
      description: 'Description of Sanvello.',
      website: 'https://www.sanvello.com/',
      offersOnlineCounseling: false,
    },
    {
      id: 8,
      category: 'Telehealth Services',
      name: 'Teladoc',
      description: 'Description of Teladoc.',
      website: 'https://www.teladoc.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 9,
      category: 'Telehealth Services',
      name: 'Amwell',
      description: 'Description of Amwell.',
      website: 'https://www.amwell.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 10,
      category: 'Telehealth Services',
      name: 'Doctor on Demand',
      description: 'Description of Doctor on Demand.',
      website: 'https://www.doctorondemand.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 11,
      category: 'Nonprofit Organizations',
      name: 'National Alliance on Mental Illness (NAMI)',
      description: 'Description of NAMI.',
      website: 'https://www.nami.org/',
      offersOnlineCounseling: false,
    },
    {
      id: 12,
      category: 'Nonprofit Organizations',
      name: 'Mental Health America (MHA)',
      description: 'Description of MHA.',
      website: 'https://www.mhanational.org/',
      offersOnlineCounseling: false,
    },
    {
      id: 13,
      category: 'Nonprofit Organizations',
      name: 'Crisis Text Line',
      description: 'Description of Crisis Text Line.',
      website: 'https://www.crisistextline.org/',
      offersOnlineCounseling: false,
    },
    {
      id: 14,
      category: 'Nonprofit Organizations',
      name: 'The Trevor Project (for LGBTQ+ youth)',
      description: 'Description of The Trevor Project.',
      website: 'https://www.thetrevorproject.org/',
      offersOnlineCounseling: false,
    },
  ];
  
  export default mentalHealthResources;
  