const mentalHealthResources = [
    {
      id: 1,
      category: 'Online Therapy Platforms',
      name: 'BetterHelp',
      description: 'BetterHelp offers licensed therapists who specialize in issues such as depression, anxiety, relationships, trauma, grief, and more. Therapy sessions are available via text, chat, phone, and video.',
      website: 'https://www.betterhelp.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 2,
      category: 'Online Therapy Platforms',
      name: 'Talkspace',
      description: 'Talkspace provides online therapy with licensed therapists, catering to a range of mental health issues. Services include individual therapy, couples therapy, and psychiatry, accessible through messaging and live video sessions.',
      website: 'https://www.talkspace.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 3,
      category: 'Online Therapy Platforms',
      name: '7 Cups',
      description: '7 Cups offers emotional support and counseling from trained volunteer listeners, with the option to access licensed therapists. The platform is available 24/7 and provides a community for individuals seeking support.',
      website: 'https://www.7cups.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 4,
      category: 'Online Therapy Platforms',
      name: 'Regain',
      description: 'Regain focuses on online counseling for couples, helping them navigate relationship issues. Therapy is provided via messaging, phone, and video by licensed therapists.',
      website: 'https://www.regain.us/',
      offersOnlineCounseling: true,
    },
    {
      id: 5,
      category: 'Mental Health Apps',
      name: 'Calm',
      description: 'Calm is a popular app for meditation, sleep, and relaxation. It offers guided meditations, Sleep Stories, breathing programs, and relaxing music.',
      website: 'https://www.calm.com/',
      offersOnlineCounseling: false,
    },
    {
      id: 6,
      category: 'Mental Health Apps',
      name: 'Headspace',
      description: 'Headspace offers guided meditation sessions and mindfulness training, aiming to improve mental well-being. The app covers topics like stress, sleep, focus, and anxiety.',
      website: 'https://www.headspace.com/',
      offersOnlineCounseling: false,
    },
    {
      id: 7,
      category: 'Mental Health Apps',
      name: 'Sanvello (formerly Pacifica)',
      description: 'Description of Sanvello provides tools for stress, anxiety, and depression based on cognitive behavioral therapy (CBT). Features include mood tracking, guided journeys, and community support.',
      website: 'https://www.sanvello.com/',
      offersOnlineCounseling: false,
    },
    {
      id: 8,
      category: 'Telehealth Services',
      name: 'Teladoc',
      description: 'Teladoc offers access to a wide range of healthcare services, including mental health support. Patients can connect with licensed doctors and therapists via phone, video, or app. of Teladoc.',
      website: 'https://www.teladoc.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 9,
      category: 'Telehealth Services',
      name: 'Amwell',
      description: 'Amwell provides telehealth services with licensed providers for various medical and mental health issues, including urgent care, therapy, and psychiatry.',
      website: 'https://www.amwell.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 10,
      category: 'Telehealth Services',
      name: 'Doctor on Demand',
      description: 'Doctor on Demand offers video appointments with board-certified physicians, psychologists, and psychiatrists for a wide range of health services, including mental health.',
      website: 'https://www.doctorondemand.com/',
      offersOnlineCounseling: true,
    },
    {
      id: 11,
      category: 'Nonprofit Organizations',
      name: 'National Alliance on Mental Illness (NAMI)',
      description: 'NAMI is dedicated to building better lives for Americans affected by mental illness through advocacy, education, support, and public awareness programs.',
      website: 'https://www.nami.org/',
      offersOnlineCounseling: false,
    },
    {
      id: 12,
      category: 'Nonprofit Organizations',
      name: 'Mental Health America (MHA)',
      description: 'MHA promotes mental health as a critical part of overall wellness through advocacy, education, research, and services.',
      website: 'https://www.mhanational.org/',
      offersOnlineCounseling: false,
    },
    {
      id: 13,
      category: 'Nonprofit Organizations',
      name: 'Crisis Text Line',
      description: 'Crisis Text Line provides free, 24/7, confidential text message support for people in crisis, connecting them with trained crisis counselors.',
      website: 'https://www.crisistextline.org/',
      offersOnlineCounseling: false,
    },
    {
      id: 14,
      category: 'Nonprofit Organizations',
      name: 'The Trevor Project (for LGBTQ+ youth)',
      description: 'The Trevor Project offers crisis intervention and suicide prevention services to LGBTQ+ young people under 25, including a 24/7 crisis hotline, chat, and text.',
      website: 'https://www.thetrevorproject.org/',
      offersOnlineCounseling: false,
    },
  ];
  
  export default mentalHealthResources;
  